server:
  port: 8007
spring:
  application:
    name: guli-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8100/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    guli-statistics:
       path: /statistics/**
       serviceId: guli-statistics
    guli-ucenter:
           path: /ucenter/**
           serviceId: guli-ucenter
    guli-edu:
           path: /edu/**
           serviceId: guli-edu
